### ISSUE TITLE
infografia

### ISSUE THREAD

**Issue by Roldanuriel** [SistemasTecTlaxiaco/actividad-1-infografia-Roldanuriel#1]
![Infografía Avances de Tecnología Moderno Azul](https://github.com/user-attachments/assets/95bc86c4-12d5-4e90-9dd1-ea5eaf649913)

**Comment by Blanca-estela-valerio-rivero** [comment]
De acuerdo a la rubrica tiene un 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
